// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/cart/data/entities/cart_item_entity.dart';
import 'features/cart/data/entities/cart_promo_entity.dart';
import 'features/products/data/entities/product_category_entity.dart';
import 'features/products/data/entities/product_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4398106125119480467),
    name: 'CartItemEntity',
    lastPropertyId: const obx_int.IdUid(7, 5329936059691067534),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1473345860896347184),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5795155396974454926),
        name: 'productId',
        type: 6,
        flags: 32808,
        indexId: const obx_int.IdUid(1, 8160892466341074937),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6574863927752700321),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4329038674962205204),
        name: 'subtitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3161046299101270147),
        name: 'thumbnail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3929626872228172177),
        name: 'unitPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5329936059691067534),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4044685411208064454),
    name: 'CartPromoEntity',
    lastPropertyId: const obx_int.IdUid(3, 5778036320500150573),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 907268724693919759),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4083982683634713996),
        name: 'code',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5778036320500150573),
        name: 'discountPercentage',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1935027286795338042),
    name: 'ProductCategoryEntity',
    lastPropertyId: const obx_int.IdUid(3, 7449672658549171045),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7241405818109104052),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2460386974778915066),
        name: 'slug',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(2, 1095129117367154737),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7449672658549171045),
        name: 'name',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 3787411160870313844),
    name: 'ProductEntity',
    lastPropertyId: const obx_int.IdUid(14, 2515871009861193364),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6317362723521603818),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6836261285014759625),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 800458165040236116),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5856684362154195856),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7819586831413743604),
        name: 'price',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1711216181145446379),
        name: 'discountPercentage',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2537558733774731336),
        name: 'rating',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1207239369521381123),
        name: 'stock',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6347474868260678721),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6529921242367717475),
        name: 'brand',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3153446516663948474),
        name: 'sku',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 1611198283932901625),
        name: 'availabilityStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5929341014248594007),
        name: 'thumbnail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2515871009861193364),
        name: 'images',
        type: 30,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 3787411160870313844),
    lastIndexId: const obx_int.IdUid(2, 1095129117367154737),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CartItemEntity: obx_int.EntityDefinition<CartItemEntity>(
      model: _entities[0],
      toOneRelations: (CartItemEntity object) => [],
      toManyRelations: (CartItemEntity object) => {},
      getId: (CartItemEntity object) => object.id,
      setId: (CartItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CartItemEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final subtitleOffset = fbb.writeString(object.subtitle);
        final thumbnailOffset = fbb.writeString(object.thumbnail);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.productId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, subtitleOffset);
        fbb.addOffset(4, thumbnailOffset);
        fbb.addFloat64(5, object.unitPrice);
        fbb.addInt64(6, object.quantity);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final productIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final subtitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final thumbnailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final unitPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = CartItemEntity(
          id: idParam,
          productId: productIdParam,
          title: titleParam,
          subtitle: subtitleParam,
          thumbnail: thumbnailParam,
          unitPrice: unitPriceParam,
          quantity: quantityParam,
        );

        return object;
      },
    ),
    CartPromoEntity: obx_int.EntityDefinition<CartPromoEntity>(
      model: _entities[1],
      toOneRelations: (CartPromoEntity object) => [],
      toManyRelations: (CartPromoEntity object) => {},
      getId: (CartPromoEntity object) => object.id,
      setId: (CartPromoEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CartPromoEntity object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, codeOffset);
        fbb.addFloat64(2, object.discountPercentage);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final discountPercentageParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = CartPromoEntity(
          id: idParam,
          code: codeParam,
          discountPercentage: discountPercentageParam,
        );

        return object;
      },
    ),
    ProductCategoryEntity: obx_int.EntityDefinition<ProductCategoryEntity>(
      model: _entities[2],
      toOneRelations: (ProductCategoryEntity object) => [],
      toManyRelations: (ProductCategoryEntity object) => {},
      getId: (ProductCategoryEntity object) => object.id,
      setId: (ProductCategoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProductCategoryEntity object, fb.Builder fbb) {
        final slugOffset = fbb.writeString(object.slug);
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, slugOffset);
        fbb.addOffset(2, nameOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final slugParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = ProductCategoryEntity(
          id: idParam,
          slug: slugParam,
          name: nameParam,
        );

        return object;
      },
    ),
    ProductEntity: obx_int.EntityDefinition<ProductEntity>(
      model: _entities[3],
      toOneRelations: (ProductEntity object) => [],
      toManyRelations: (ProductEntity object) => {},
      getId: (ProductEntity object) => object.id,
      setId: (ProductEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProductEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = fbb.writeString(object.description);
        final categoryOffset = fbb.writeString(object.category);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final brandOffset = fbb.writeString(object.brand);
        final skuOffset = fbb.writeString(object.sku);
        final availabilityStatusOffset = fbb.writeString(
          object.availabilityStatus,
        );
        final thumbnailOffset = fbb.writeString(object.thumbnail);
        final imagesOffset = fbb.writeList(
          object.images.map(fbb.writeString).toList(growable: false),
        );
        fbb.startTable(15);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, categoryOffset);
        fbb.addFloat64(4, object.price);
        fbb.addFloat64(5, object.discountPercentage);
        fbb.addFloat64(6, object.rating);
        fbb.addInt64(7, object.stock);
        fbb.addOffset(8, tagsOffset);
        fbb.addOffset(9, brandOffset);
        fbb.addOffset(10, skuOffset);
        fbb.addOffset(11, availabilityStatusOffset);
        fbb.addOffset(12, thumbnailOffset);
        fbb.addOffset(13, imagesOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final priceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final discountPercentageParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final ratingParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final stockParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 20, []);
        final brandParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final skuParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final availabilityStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final thumbnailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final imagesParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 30, []);
        final object = ProductEntity(
          id: idParam,
          title: titleParam,
          description: descriptionParam,
          category: categoryParam,
          price: priceParam,
          discountPercentage: discountPercentageParam,
          rating: ratingParam,
          stock: stockParam,
          tags: tagsParam,
          brand: brandParam,
          sku: skuParam,
          availabilityStatus: availabilityStatusParam,
          thumbnail: thumbnailParam,
          images: imagesParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CartItemEntity] entity fields to define ObjectBox queries.
class CartItemEntity_ {
  /// See [CartItemEntity.id].
  static final id = obx.QueryIntegerProperty<CartItemEntity>(
    _entities[0].properties[0],
  );

  /// See [CartItemEntity.productId].
  static final productId = obx.QueryIntegerProperty<CartItemEntity>(
    _entities[0].properties[1],
  );

  /// See [CartItemEntity.title].
  static final title = obx.QueryStringProperty<CartItemEntity>(
    _entities[0].properties[2],
  );

  /// See [CartItemEntity.subtitle].
  static final subtitle = obx.QueryStringProperty<CartItemEntity>(
    _entities[0].properties[3],
  );

  /// See [CartItemEntity.thumbnail].
  static final thumbnail = obx.QueryStringProperty<CartItemEntity>(
    _entities[0].properties[4],
  );

  /// See [CartItemEntity.unitPrice].
  static final unitPrice = obx.QueryDoubleProperty<CartItemEntity>(
    _entities[0].properties[5],
  );

  /// See [CartItemEntity.quantity].
  static final quantity = obx.QueryIntegerProperty<CartItemEntity>(
    _entities[0].properties[6],
  );
}

/// [CartPromoEntity] entity fields to define ObjectBox queries.
class CartPromoEntity_ {
  /// See [CartPromoEntity.id].
  static final id = obx.QueryIntegerProperty<CartPromoEntity>(
    _entities[1].properties[0],
  );

  /// See [CartPromoEntity.code].
  static final code = obx.QueryStringProperty<CartPromoEntity>(
    _entities[1].properties[1],
  );

  /// See [CartPromoEntity.discountPercentage].
  static final discountPercentage = obx.QueryDoubleProperty<CartPromoEntity>(
    _entities[1].properties[2],
  );
}

/// [ProductCategoryEntity] entity fields to define ObjectBox queries.
class ProductCategoryEntity_ {
  /// See [ProductCategoryEntity.id].
  static final id = obx.QueryIntegerProperty<ProductCategoryEntity>(
    _entities[2].properties[0],
  );

  /// See [ProductCategoryEntity.slug].
  static final slug = obx.QueryStringProperty<ProductCategoryEntity>(
    _entities[2].properties[1],
  );

  /// See [ProductCategoryEntity.name].
  static final name = obx.QueryStringProperty<ProductCategoryEntity>(
    _entities[2].properties[2],
  );
}

/// [ProductEntity] entity fields to define ObjectBox queries.
class ProductEntity_ {
  /// See [ProductEntity.id].
  static final id = obx.QueryIntegerProperty<ProductEntity>(
    _entities[3].properties[0],
  );

  /// See [ProductEntity.title].
  static final title = obx.QueryStringProperty<ProductEntity>(
    _entities[3].properties[1],
  );

  /// See [ProductEntity.description].
  static final description = obx.QueryStringProperty<ProductEntity>(
    _entities[3].properties[2],
  );

  /// See [ProductEntity.category].
  static final category = obx.QueryStringProperty<ProductEntity>(
    _entities[3].properties[3],
  );

  /// See [ProductEntity.price].
  static final price = obx.QueryDoubleProperty<ProductEntity>(
    _entities[3].properties[4],
  );

  /// See [ProductEntity.discountPercentage].
  static final discountPercentage = obx.QueryDoubleProperty<ProductEntity>(
    _entities[3].properties[5],
  );

  /// See [ProductEntity.rating].
  static final rating = obx.QueryDoubleProperty<ProductEntity>(
    _entities[3].properties[6],
  );

  /// See [ProductEntity.stock].
  static final stock = obx.QueryIntegerProperty<ProductEntity>(
    _entities[3].properties[7],
  );

  /// See [ProductEntity.tags].
  static final tags = obx.QueryStringVectorProperty<ProductEntity>(
    _entities[3].properties[8],
  );

  /// See [ProductEntity.brand].
  static final brand = obx.QueryStringProperty<ProductEntity>(
    _entities[3].properties[9],
  );

  /// See [ProductEntity.sku].
  static final sku = obx.QueryStringProperty<ProductEntity>(
    _entities[3].properties[10],
  );

  /// See [ProductEntity.availabilityStatus].
  static final availabilityStatus = obx.QueryStringProperty<ProductEntity>(
    _entities[3].properties[11],
  );

  /// See [ProductEntity.thumbnail].
  static final thumbnail = obx.QueryStringProperty<ProductEntity>(
    _entities[3].properties[12],
  );

  /// See [ProductEntity.images].
  static final images = obx.QueryStringVectorProperty<ProductEntity>(
    _entities[3].properties[13],
  );
}
