// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/cart/data/entities/cart_item_entity.dart';
import 'features/cart/data/entities/cart_promo_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4398106125119480467),
    name: 'CartItemEntity',
    lastPropertyId: const obx_int.IdUid(7, 5329936059691067534),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1473345860896347184),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5795155396974454926),
        name: 'productId',
        type: 6,
        flags: 32808,
        indexId: const obx_int.IdUid(1, 8160892466341074937),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6574863927752700321),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4329038674962205204),
        name: 'subtitle',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3161046299101270147),
        name: 'thumbnail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3929626872228172177),
        name: 'unitPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5329936059691067534),
        name: 'quantity',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4044685411208064454),
    name: 'CartPromoEntity',
    lastPropertyId: const obx_int.IdUid(3, 5778036320500150573),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 907268724693919759),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4083982683634713996),
        name: 'code',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5778036320500150573),
        name: 'discountPercentage',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 4044685411208064454),
    lastIndexId: const obx_int.IdUid(1, 8160892466341074937),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CartItemEntity: obx_int.EntityDefinition<CartItemEntity>(
      model: _entities[0],
      toOneRelations: (CartItemEntity object) => [],
      toManyRelations: (CartItemEntity object) => {},
      getId: (CartItemEntity object) => object.id,
      setId: (CartItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CartItemEntity object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final subtitleOffset = fbb.writeString(object.subtitle);
        final thumbnailOffset = fbb.writeString(object.thumbnail);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.productId);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, subtitleOffset);
        fbb.addOffset(4, thumbnailOffset);
        fbb.addFloat64(5, object.unitPrice);
        fbb.addInt64(6, object.quantity);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final productIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final subtitleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final thumbnailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final unitPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final quantityParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = CartItemEntity(
          id: idParam,
          productId: productIdParam,
          title: titleParam,
          subtitle: subtitleParam,
          thumbnail: thumbnailParam,
          unitPrice: unitPriceParam,
          quantity: quantityParam,
        );

        return object;
      },
    ),
    CartPromoEntity: obx_int.EntityDefinition<CartPromoEntity>(
      model: _entities[1],
      toOneRelations: (CartPromoEntity object) => [],
      toManyRelations: (CartPromoEntity object) => {},
      getId: (CartPromoEntity object) => object.id,
      setId: (CartPromoEntity object, int id) {
        object.id = id;
      },
      objectToFB: (CartPromoEntity object, fb.Builder fbb) {
        final codeOffset = fbb.writeString(object.code);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, codeOffset);
        fbb.addFloat64(2, object.discountPercentage);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final codeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final discountPercentageParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = CartPromoEntity(
          id: idParam,
          code: codeParam,
          discountPercentage: discountPercentageParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CartItemEntity] entity fields to define ObjectBox queries.
class CartItemEntity_ {
  /// See [CartItemEntity.id].
  static final id = obx.QueryIntegerProperty<CartItemEntity>(
    _entities[0].properties[0],
  );

  /// See [CartItemEntity.productId].
  static final productId = obx.QueryIntegerProperty<CartItemEntity>(
    _entities[0].properties[1],
  );

  /// See [CartItemEntity.title].
  static final title = obx.QueryStringProperty<CartItemEntity>(
    _entities[0].properties[2],
  );

  /// See [CartItemEntity.subtitle].
  static final subtitle = obx.QueryStringProperty<CartItemEntity>(
    _entities[0].properties[3],
  );

  /// See [CartItemEntity.thumbnail].
  static final thumbnail = obx.QueryStringProperty<CartItemEntity>(
    _entities[0].properties[4],
  );

  /// See [CartItemEntity.unitPrice].
  static final unitPrice = obx.QueryDoubleProperty<CartItemEntity>(
    _entities[0].properties[5],
  );

  /// See [CartItemEntity.quantity].
  static final quantity = obx.QueryIntegerProperty<CartItemEntity>(
    _entities[0].properties[6],
  );
}

/// [CartPromoEntity] entity fields to define ObjectBox queries.
class CartPromoEntity_ {
  /// See [CartPromoEntity.id].
  static final id = obx.QueryIntegerProperty<CartPromoEntity>(
    _entities[1].properties[0],
  );

  /// See [CartPromoEntity.code].
  static final code = obx.QueryStringProperty<CartPromoEntity>(
    _entities[1].properties[1],
  );

  /// See [CartPromoEntity.discountPercentage].
  static final discountPercentage = obx.QueryDoubleProperty<CartPromoEntity>(
    _entities[1].properties[2],
  );
}
